#!/usr/bin/env python
"""gsm2fastq v0.1"""
import sys
import os
import json
import argparse
import GEOparse


def parse(args):

    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter
    )

    p.add_argument("term",
                   help="GEO accession",
                   metavar="GSM"
                   )
    p.add_argument("email",
                   help="e-mail address for Entrez API",
                   metavar="EMAIL"
                   )
    p.add_argument("-o", "--outdir",
                   dest="outdir",
                   help="output directory, defaults to '.'",
                   metavar="DIR",
                   default="./"
                   )
    p.add_argument("-f", "--filetype",
                   dest="filetype",
                   help="filetype to download, defaults to 'fastq'",
                   default="fastq",
                   choices=('sra', 'fastq')
                   )
    return p.parse_args(args)


if __name__ == "__main__":
    args = parse(sys.argv[1:])
    if not args.term.startswith("GSM"):
        raise NotImplementedError("only GSM ids work for now!")
    gsm = GEOparse.get_GEO(args.term)
    downloaded_files = gsm.download_SRA(
            args.email,
            directory=args.outdir,
            filetype=args.filetype,
            aspera="ASPERA_HOME" in os.environ,
            )
    print("{}".format(json.dumps(downloaded_files, indent=4)))
